extends Node
## Lean audio hub. All SFX/music route through here so the game has one place
## to control volume, ducking, etc.
##
## Placeholder-friendly: no sound files ship yet, so play_sfx() is a safe no-op
## until streams are registered. The gameplay calls are already wired, so
## dropping in real audio later needs no changes to callers.

# Placeholder SFX generated by tools/GenSfx. Loaded if present; missing files
# just leave that cue silent.
const SFX_FILES := {
	&"pickup": "res://audio/pickup.wav",
	&"combine": "res://audio/combine.wav",
	&"success": "res://audio/success.wav",
	&"error": "res://audio/error.wav",
	&"ui": "res://audio/ui.wav",
	&"footstep": "res://audio/footstep.wav",
	&"dialogue": "res://audio/dialogue.wav",
}

var _sfx: Dictionary = {}          # name -> AudioStream
var _sfx_players: Array[AudioStreamPlayer] = []
var _next_player := 0
var _music_player: AudioStreamPlayer


func _ready() -> void:
	# A small pool so overlapping cues (footsteps + a pickup) don't cut off.
	for i in 6:
		var p := AudioStreamPlayer.new()
		p.bus = &"Master"
		add_child(p)
		_sfx_players.append(p)
	_music_player = AudioStreamPlayer.new()
	_music_player.bus = &"Master"
	add_child(_music_player)

	for name in SFX_FILES:
		var path: String = SFX_FILES[name]
		if ResourceLoader.exists(path):
			_sfx[name] = load(path)


## Register a stream under a name (call from a boot step once audio exists).
func register_sfx(name: StringName, stream: AudioStream) -> void:
	_sfx[name] = stream


func play_sfx(name: StringName, pitch: float = 1.0) -> void:
	var stream: AudioStream = _sfx.get(name)
	if stream == null:
		return  # placeholder: nothing registered yet
	var p := _sfx_players[_next_player]
	_next_player = (_next_player + 1) % _sfx_players.size()
	p.stream = stream
	p.pitch_scale = pitch
	p.play()


func play_music(stream: AudioStream) -> void:
	if stream == null:
		return
	_music_player.stream = stream
	_music_player.play()


func stop_music() -> void:
	_music_player.stop()
